---

dependency:
  name: galaxy
  enabled: yes
  options:
    ignore-certs: yes
    ignore-errors: yes
    role-file: "${MOLECULE_SCENARIO_DIRECTORY}/requirements.yml"
    requirements-file: "${MOLECULE_SCENARIO_DIRECTORY}/requirements.yml"
driver:
  name: docker
lint: "${MOLECULE_SCENARIO_DIRECTORY}/linters.sh"
platforms:
  - name: "centos6-${INSTANCE_UUID:-1}"
    image: centos:6
    dockerfile: Dockerfile.centos6.j2
    # Only required for systemd enabled containers
    # dockerfile: Dockerfile.systemd.j2
    # command: /sbin/init
    # tmpfs:
    #   - /run
    #   - /tmp
    # volumes:
    #   - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - molecule_hosts
      - molecule_hosts_centos
      - molecule_hosts_centos_6
  - name: "centos7-${INSTANCE_UUID:-1}"
    image: centos:7
    # Only required for systemd enabled containers
    # dockerfile: Dockerfile.systemd.j2
    # command: /sbin/init
    # tmpfs:
    #   - /run
    #   - /tmp
    # volumes:
    #   - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - molecule_hosts
      - molecule_hosts_centos
      - molecule_hosts_centos_7
  - name: "centos8-${INSTANCE_UUID:-1}"
    image: centos:8
    # Only required for systemd enabled containers
    # dockerfile: Dockerfile.systemd.j2
    # command: /sbin/init
    # tmpfs:
    #   - /run
    #   - /tmp
    # volumes:
    #   - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - molecule_hosts
      - molecule_hosts_centos
      - molecule_hosts_centos_8
  - name: "fedora33-${INSTANCE_UUID:-1}"
    image: fedora:33
    # Only required for systemd enabled containers
    # dockerfile: Dockerfile.systemd.j2
    # command: /sbin/init
    # tmpfs:
    #   - /run
    #   - /tmp
    # volumes:
    #   - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - molecule_hosts
      - molecule_hosts_fedora
      - molecule_hosts_fedora_33
  - name: "fedora34-${INSTANCE_UUID:-1}"
    image: fedora:34
    # Only required for systemd enabled containers
    # dockerfile: Dockerfile.systemd.j2
    # command: /sbin/init
    # tmpfs:
    #   - /run
    #   - /tmp
    # volumes:
    #   - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - molecule_hosts
      - molecule_hosts_fedora
      - molecule_hosts_fedora_34
provisioner:
  name: ansible
  config_options:
    defaults:
      callback_enabled: profile_tasks
      action_plugins: $PWD/action_plugins
  inventory:
    hosts:
      molecule_hosts:
        vars:
      molecule_hosts_fedora:
        vars:
          ansible_python_interpreter: /usr/bin/python3
verifier:
  name: ansible
